services:
  mail:
    image: bytemark/smtp
    restart: unless-stopped
    networks:
      - plausible-internal

  plausible_db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    networks:
      - plausible-internal

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: unless-stopped
    volumes:
      - ./data/event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    networks:
      - plausible-internal
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: unless-stopped
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    env_file:
      - plausible-conf.env
    networks:
      - plausible-internal
      - services
      
networks:
  plausible-internal:
    external: true
  services:
    external: true

